language: java
script:
- mvn clean package
deploy:
  provider: heroku
  api_key:
    secure: "J6H4HFh3tqRSx/st1GhBAVtybpqtB7CJhNZay/ON3b8xFl/fF/o0RoNVUfzrv/4klRRtCT+dtoszPHJPee3JRSWq6rRkKHVb7mk0Pks0bQhu6VTENZSPPWajUDYkUQMgLuMkHhxCiMvNRlCa8vtRTcGtxMhdkJxaL5GcMv0tzXHHg5AD+nQMl2WzEN0HjqrGDpRQqf/KH8sjihCs/VYvWKqNZIa0JSHdQHNvMWSfG0daCtNd+HdoJiCyfFGspCnMbz6dv23kp/bT1IxCE6Ir5J/jRvJaUTHxUD0aHSV8LVG21iCGsjF6rPZ8myle05453TCrg2lWinT9D53HMENHTD8YvWnC8rtqxNZ0JDQV6yzc+b6E+fVQze3ax5wwWcw7euwmcB3xoBrYIguBesSHtuGqirkvbk10V4zKn8j284MyMAAqcMpZyJSBMx/F0V7Ii24U0GnXnduEoyPu13J0716cr5eEc35/y2XnGsXAYF/GWbGb1T4U7wPZHHrR/88xOhMlYmS0YUr6g8gFn7J6F0kEnIgWo4jDUkPxLc0VUhO5kQizuH9eKL1M8J7waQuTZmzCVWQneme5xEoa78cLFf9dkGJOGSdHwhkKtwKXZccVabbgBUr2eAf+CcwWfq9rc2rUv7w15DIVkIyz3XUVvzRZs6B2ZDUDrNq/CvXpneo="
  app:
    master: kursovaya13test
    
