language: java
script:
- mvn clean package
deploy:
  provider: heroku
  api_key:
    secure: "SBau5Ob6GNMO2vEHm492hvCD+lDYxcOdUdBan4SodAnp8W6bGL0wXYoXkbWzea2BhhLyqdBsASkaAhiaewGtS9Lblqgx4dP1PInv5jXYTFCeHphM4vjuSY+tv+QcEplZNXjbjKdBY+0+JYm+Q2QPUtFlPh+acCZG6EghiHcbBN+/8VogcjeoZ9MSvvZTPGNybF7Q164gCDIHaPKEGhyaVVir/ywK+6jTtglVp1oMgzl4fSE9A+7xSibGwPc3rkLvxQY2mMzQWbHjDhom1035h6lUumICnTq9vdB04Jv1eadkEktKYQYyl0JsyepDmTbbICVueE+Y++kFk4D2qU2KWvtpomcGqnu79Mu0dyWGO8qZfqSLys7pXnZOeWL9LWOuTA9Br2aZPUpRxXAjTsPKVB0oinbCSpHbF3oLa2wkAagvfAifnh+FfnxOdcgVaSUfV2dXSwkwh9LRbGa9T60PhhUEAeJrvYH5bGY7G4sDEa7tVzUY/oOqVirf7oQruoSvT+q/XeRNwMNHl3gidyQa0uAli2KqsJnNAnQwzrOBgEh0ACao53aK6+o8TfzGY+dJdWJLJcIBebUIxAmeYuhvGbV4K2c9g7QYWgT2o1YgGAvQw+A9sZ24WnCyFpV6MNuVPLPeM0BHXkNoN2WPJdWuHDpxztY98vdGShX0S2kwlVI="
  app:
    master: Kursovaya_13
    
