import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

	public class ChangeComboBoxListener implements ActionListener {
		public void actionPerformed(ActionEvent e) {
	int i = MathRgr.reklama.getSelectedIndex();// Получение значения changeBox
	switch(i) {
	case 0: {
		MathRgr.w = 1; MathRgr.n = 1; MathRgr.f = 1; MathRgr.j = 1; MathRgr.c = 1; MathRgr.a = 1; 
		MathRgr.T = 30;
		MathRgr.bx4.setVisible(false);
		MathRgr.bx4.setEnabled(false);
		MathRgr.bx5.setVisible(false);
		MathRgr.bx5.setEnabled(false);
		MathRgr.bx6.setVisible(false);
		MathRgr.bx6.setEnabled(false);
		MathRgr.box.setVisible(false);
		MathRgr.box.setEnabled(false);
		MathRgr.box1.setVisible(false);
		MathRgr.box1.setEnabled(false);
		MathRgr.lb15.setVisible(false);
		MathRgr.lb16.setVisible(false);
		MathRgr.lb11.setVisible(false);
		MathRgr.reklama4.setVisible(false);
		MathRgr.reklama4.setEnabled(false);
		MathRgr.lb9.setVisible(false);
		MathRgr.lb10.setVisible(false);
		MathRgr.bx.setVisible(false);
		MathRgr.bx1.setVisible(false);
		MathRgr.bx2.setVisible(false);
		MathRgr.bx3.setVisible(false);
		MathRgr.lb.setVisible(false);
		MathRgr.lb4.setVisible(false);
		MathRgr.text.setEnabled(false);
		MathRgr.text.setVisible(false);
		MathRgr.text2.setEnabled(false);
		MathRgr.text2.setVisible(false);
		MathRgr.reklama2.setVisible(false);
		MathRgr.text3.setEnabled(false);
		MathRgr.text3.setVisible(false);
		MathRgr.text4.setEnabled(false);
		MathRgr.text4.setVisible(false);
		MathRgr.lb.setVisible(false);
		MathRgr.lb5.setVisible(false);
		MathRgr.reklama3.setVisible(false);
		MathRgr.text1.setEnabled(true);
		MathRgr.text1.setVisible(true);
		MathRgr.lb1.setVisible(true);
		MathRgr.lb2.setVisible(true);
		MathRgr.lb3.setVisible(true);
		MathRgr.lb8.setVisible(true);
		MathRgr.lokolo.setVisible(true);
		MathRgr.reklama1.setVisible(true);
		MathRgr.text7.setVisible(true);
		MathRgr.text7.setEnabled(true);
		
		break;
	}
	case 1: {
		MathRgr.w = 1; MathRgr.n = 1; MathRgr.f = 1; MathRgr.j = 1; MathRgr.c = 1; MathRgr.a = 1; 
		MathRgr.T = 0.8;
		MathRgr.reklama5.setVisible(false);
		MathRgr.reklama5.setEnabled(false);
		MathRgr.reklama6.setVisible(false);
		MathRgr.reklama6.setEnabled(false);
		MathRgr.lb13.setVisible(false);
		MathRgr.lb14.setVisible(false);
		MathRgr.bx4.setVisible(false);
		MathRgr.bx4.setEnabled(false);
		MathRgr.bx5.setVisible(false);
		MathRgr.bx5.setEnabled(false);
		MathRgr.bx6.setVisible(false);
		MathRgr.bx6.setEnabled(false);
		MathRgr.box.setVisible(false);
		MathRgr.box.setEnabled(false);
		MathRgr.box1.setVisible(false);
		MathRgr.box1.setEnabled(false);
		MathRgr.lb15.setVisible(false);
		MathRgr.lb16.setVisible(false);
		MathRgr.text7.setVisible(false);
		MathRgr.text7.setEnabled(false);
		MathRgr.text1.setEnabled(false);
		MathRgr.text1.setVisible(false);
		MathRgr.lb1.setVisible(false);
		MathRgr.lb2.setVisible(false);
		MathRgr.lb3.setVisible(false);
		MathRgr.lokolo.setVisible(false);
		MathRgr.reklama1.setVisible(false);
		MathRgr.text3.setEnabled(false);
		MathRgr.text3.setVisible(false);
		MathRgr.text4.setEnabled(false);
		MathRgr.text4.setVisible(false);
		MathRgr.lb.setVisible(false);
		MathRgr.lb5.setVisible(false);
		MathRgr.lb8.setVisible(false);
		MathRgr.reklama3.setVisible(false);
		MathRgr.lb.setVisible(true);
		MathRgr.lb4.setVisible(true);		
		MathRgr.text.setEnabled(true);
		MathRgr.text.setVisible(true);
		MathRgr.text2.setEnabled(true);
		MathRgr.text2.setVisible(true);
		MathRgr.reklama2.setVisible(true);
		MathRgr.lb11.setVisible(true);
		MathRgr.reklama4.setVisible(true);
		MathRgr.reklama4.setEnabled(true);
		
		break;
	}
	case 2:{
		MathRgr.w = 1; MathRgr.n = 1; MathRgr.f = 1; MathRgr.j = 1; MathRgr.c = 1; MathRgr.a = 1; 
		MathRgr.T = 0.2;
		MathRgr.reklama5.setVisible(false);
		MathRgr.reklama5.setEnabled(false);
		MathRgr.reklama6.setVisible(false);
		MathRgr.reklama6.setEnabled(false);
		MathRgr.lb13.setVisible(false);
		MathRgr.lb14.setVisible(false);
		MathRgr.text7.setVisible(false);
		MathRgr.text7.setEnabled(false);
		MathRgr.lb9.setVisible(false);
		MathRgr.lb10.setVisible(false);
		MathRgr.bx.setVisible(false);
		MathRgr.bx1.setVisible(false);
		MathRgr.bx2.setVisible(false);
		MathRgr.bx3.setVisible(false);
		MathRgr.lb11.setVisible(false);
		MathRgr.reklama4.setVisible(false);
		MathRgr.reklama4.setEnabled(false);
		MathRgr.lb.setVisible(false);
		MathRgr.lb4.setVisible(false);
		MathRgr.text.setEnabled(false);
		MathRgr.text.setVisible(false);
		MathRgr.text2.setEnabled(false);
		MathRgr.text2.setVisible(false);
		MathRgr.reklama2.setVisible(false);
		MathRgr.text1.setEnabled(false);
		MathRgr.text1.setVisible(false);
		MathRgr.lb1.setVisible(false);
		MathRgr.lb2.setVisible(false);
		MathRgr.lb3.setVisible(false);
		MathRgr.lokolo.setVisible(false);
		MathRgr.lb8.setVisible(false);
		MathRgr.reklama1.setVisible(false);
		MathRgr.text3.setEnabled(true);
		MathRgr.text3.setVisible(true);
		MathRgr.text4.setEnabled(true);
		MathRgr.text4.setVisible(true);
		MathRgr.lb.setVisible(true);
		MathRgr.lb5.setVisible(true);		
		MathRgr.reklama3.setVisible(true);
		MathRgr.bx4.setVisible(true);
		MathRgr.bx4.setEnabled(true);
		MathRgr.bx5.setVisible(true);
		MathRgr.bx5.setEnabled(true);
		MathRgr.bx6.setVisible(true);
		MathRgr.bx6.setEnabled(true);
		MathRgr.box.setVisible(true);
		MathRgr.box.setEnabled(true);
		MathRgr.box1.setVisible(true);
		MathRgr.box1.setEnabled(true);
		MathRgr.lb15.setVisible(true);
		MathRgr.lb16.setVisible(true);
	}
	}}
}
